# Generated by Django 6.0.5 on 2026-05-17 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=500)),
                ('word', models.CharField(max_length=100)),
                ('frequency', models.IntegerField()),
            ],
            options={
                'unique_together': {('title', 'word')},
            },
        ),
    ]
